package MainClass;
//DO NOT EDIT THIS FILE !!!
public class Main {

	public static void main(String[] args) {
		
		Board board = new Board(args[0]);
		System.out.println("puzzle:");
		board.print();
		
		char type = args[1].charAt(0);
		String heuristics = args[2];
		
		PartialSolution ps = AStar.search(board, type, heuristics);
		System.out.println("solution:");
		ps.print();
	}

}
